### ISSUE TITLE
BulkInsert throwing an exception with custom column name on SQLite

### ISSUE THREAD

**Issue by vdbwouter** [videokojot/EFCore.BulkExtensions.MIT#124]
In EFCore.BulkExtensions.MIT 8.16.1, doing a BulkInsert on a SQLite database will throw an exception if one of the entities has a custom column name. The exception might look something like this:

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=A SqliteParameter with ParameterName '@CustomColumn' is not contained by this SqliteParameterCollection.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteParameterCollection.IndexOfChecked(String parameterName)
   at Microsoft.Data.Sqlite.SqliteParameterCollection.get_Item(String parameterName)
   at EFCore.BulkExtensions.SqlAdapters.SQLite.SqliteOperationsAdapter.LoadSqliteValues[T](TableInfo tableInfo, T entity, SqliteCommand command, DbContext dbContext) in /_/EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs:line 514
   at EFCore.BulkExtensions.SqlAdapters.SQLite.SqliteOperationsAdapter.<InsertAsync>d__2`1.MoveNext() in /_/EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs:line 76
   at EFCore.BulkExtensions.SqlAdapters.SQLite.SqliteOperationsAdapter.<InsertAsync>d__2`1.MoveNext() in /_/EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs:line 105
   at EFCore.BulkExtensions.SqlAdapters.SQLite.SqliteOperationsAdapter.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in /_/EFCore.BulkExtensions/SqlAdapters/SQLite/SqLiteAdapter.cs:line 22
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in /_/EFCore.BulkExtensions/SqlBulkOperation.cs:line 57
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress) in /_/EFCore.BulkExtensions/DbContextBulkTransaction.cs:line 45
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type) in /_/EFCore.BulkExtensions/DbContextBulkExtensions.cs:line 21
   at BulkInsertRepro.Program.Main() in Sources\BulkInsertRepro\BulkInsertRepro\Program.cs:line 43
```

If the custom column name is removed, everything works as expected. However, adding a custom column name caused it to throw an exception.

This can be reproduced using the following code:

```C#
public class EntityContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }

    public string DbPath { get; }

    public EntityContext()
    {
        var folder = Environment.SpecialFolder.LocalApplicationData;
        var path = Environment.GetFolderPath(folder);
        DbPath = Path.Join(path, "entities.db");
    }

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DbPath}");
}

public class Entity
{
    public int Id { get; set; }
    [Column("Custom_Column")]
    public string CustomColumn { get; set; }
}

internal class Program
{
    static void Main()
    {
        using var db = new EntityContext();
        var entities = new[]
        {
            new Entity
            {
                CustomColumn = "test",
            },
        };
        db.BulkInsert(entities);
    }
}
```

**Comment by videokojot** [comment]
Thank you for the test and the fix, this is very much appreciated.
